name: influ-match
channels:
  - pytorch
  - nvidia
  - conda-forge
dependencies:
  - python=3.8
  - pytorch=1.13
  - torchvision=0.14
  - torchaudio=0.13
  - pytorch-cuda=11.7
  - pip
  - pip:
      - -r requirements.txt
